//! `mechos-hal` – Hardware Abstraction Layer
//!
//! The physical boundary of the OS.  This crate translates the abstract
//! intents generated by the LLM into electrical signals via registered
//! hardware drivers.
//!
//! # Modules
//!
//! - [`actuator`] – [`Actuator`] trait for position-controlled hardware
//!   (motors, servos, joints).
//! - [`relay`] – [`Relay`] trait for discrete on/off devices (solenoids,
//!   power switches).
//! - [`camera`] – [`Camera`] trait and [`CameraFrame`] type for image-capture
//!   hardware.
//! - [`pid`] – [`PidController`]: a tunable feedback control loop that
//!   smooths actuator movements without requiring micro-management from the
//!   LLM.
//! - [`registry`] – [`HardwareRegistry`]: registers drivers and dispatches
//!   [`HardwareIntent`][mechos_types::HardwareIntent] commands to them.

pub mod actuator;
pub mod camera;
pub mod pid;
pub mod registry;
pub mod relay;

pub use actuator::Actuator;
pub use camera::{Camera, CameraFrame};
pub use pid::PidController;
pub use registry::HardwareRegistry;
pub use relay::Relay;
